### ISSUE TITLE
ENH: opening screen todo

### ISSUE THREAD

**Issue by samilboyalikli** [esocraton/snake#34]
- [ ] başlangıç ekranında iki seçenek olacak
1. Start
2. Exit
- [ ] start ekranında üç seçenek olacak
1. Sonsuz Mod
2. Level Modu
3. Levellarda Sonsuz Mod
- [ ] sonsuz modda snake_game_L1.py açılacak
- [ ] level modunda L1 açılacak, 250 puan geçildiğinde L2'ye geçilecek
- [ ] L2 açılacak, 500 puan geçildiğinde L3'e geçilecek
- [ ] L3 açılacak, 750 puan geçildiğinde L4'e geçilecek
- [ ] L4 açılacak, 1000 puan geçildiğinde L5'e geçilecek
- [ ] L5 açılacak, 1250 puan geçildiğinde L6'ya geçilecek
- [ ] L6 açılacak, 1500 puan geçildiğinde L7'ye geçilecek
- [ ] L7 açılacak sonsuz gelişim olacak.
- [ ] levellarda sonsuz modda altı seçenek olacak, altı diğer dosya bulunacak hepsinde skor sonsuz olacak
