### ISSUE TITLE
ENH: todo

### ISSUE THREAD

**Issue by samilboyalikli** [esocraton/snake#35]
sayfalar birbirlerine bağlanacaklar
- [ ] first_map.py (L1)
- [ ] second_map.py (L2)
- [ ] third_map.py (L3)
- [ ] fourth_map.py (L4)
- [ ] fifth_map (L5)
- [ ] sixth_map (L6)
- [ ] seventh_map (L7)

------------------------------------------------------

- [ ] giriş ekranı düzenlenecek
