### ISSUE TITLE
BUG: snake hızlı hareketlerde tam ters istikamete giriyor

### ISSUE THREAD

**Issue by samilboyalikli** [esocraton/snake#6]
**problem**
- snake `up`, `down`, `left`, `right` gibi tuşların kullanımında tam tersi istikamette hareket etmeyecek biçimde programlandı
- ancak tam ikiden fazla tuşa ani basarak bu snake'i tam ters istikamete sokabiliyoruz
- bu durumda da dolaylı olarak tam ters istikamette hareket ettirilmiş oluyor ve oyuncu oyunu kaybediyor

**todo**
- [ ] problemin tespiti (kod olarak)
- [ ] alternatif çözümlerin saptanması
- [ ] ideal çözümün tespiti
- [ ] ideal çözümün uygulanması
